version: 2
jobs:
  build:
    working_directory: /build
    branches:
      only:
        - source
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r https://raw.githubusercontent.com/FCP-INDI/C-PAC/master/requirements.txt
            pip install git+https://github.com/FCP-INDI/C-PAC
            pip install sphinx
      - run:
          name: Build docs
          command: |
            ./bin/build

      - run:
          name: Configure git user
          command: |
            git config --global user.email "ci-build@fcp-indi.github.com"
            git config --global user.name "ci-build"
      - run:
          name: Deploy docs
          command: |
            git clone --single-branch --branch master git@github.com:FCP-INDI/fcp-indi.github.com.git /tmp/repo
            rsync -rtv ./ /tmp/repo/ --exclude '.git'
            cd /tmp/repo
            git add .
            git rm -fr docs/developer/_sources
            git rm -fr docs/user/_sources
            git rm -f .gitignore
            git commit -m "updates"
            git push -f origin master
            cd -